- name: create database credentials as secret
  k8s_v1_secret:
    state: present
    name: database-secret
    namespace: '{{ namespace }}'
    data:
      DB_HOST: "{{ 'database-service' | b64encode }}"
      DB_NAME: "{{ db_name | b64encode }}"
      DB_PASSWORD: "{{ db_password | b64encode }}"
      DB_PORT: "{{ '3306' | b64encode }}"
      DB_TYPE: "{{ 'mysql' | b64encode }}"
      DB_USER: "{{ db_user | b64encode }}"

- name: create Drupal credentials as secret
  k8s_v1_secret:
    state: present
    name: drupal-secret
    namespace: '{{ namespace }}'
    data:
      DP_USERNAME: "{{ drupal_username | b64encode }}"
      DP_PASSWORD: "{{ drupal_password | b64encode }}"
      DP_EMAIL: "{{ drupal_email | b64encode }}"

- name: create Apache config from template
  template:
    src: drupal-vhosts.conf.j2
    dest: /tmp/drupal-vhosts.conf

- name: create Apache configMap
  shell: oc create configmap apache-conf --from-file=apache-conf=/tmp/drupal-vhosts.conf

- name: create database volume claim
  k8s_v1_persistent_volume_claim:
    state: present
    name: database-volume-claim
    namespace: "{{ namespace }}"
    labels:
      app: mariadb
      service: mariadb
    access_modes:
      - ReadWriteOnce
    resources_requests:
      storage: "{{ volume_size }}"

- name: create Drupal volume claim
  k8s_v1_persistent_volume_claim:
    state: present
    name: drupal-volume-claim
    namespace: "{{ namespace }}"
    labels:
      app: drupal
      service: drupal
    access_modes:
      - ReadWriteOnce
    resources_requests:
      storage: "{{ volume_size }}"

- name: create database deployment config
  openshift_v1_deployment_config:
    state: present
    name: mariadb
    namespace: '{{ namespace }}'
    labels:
      app: mariadb
      service: mariadb
    replicas: 1
    selector:
      app: mariadb
      service: mariadb
    spec_template_metadata_labels:
      app: mariadb
      service: mariadb
    containers:
      - name: mariadb
        image: registry.access.redhat.com/rhscl/mariadb-101-rhel7
        imagePullPolicy: Always
        ports:
          - container_port: 3306
            protocol: TCP
        volume_mounts:
          - name: mariadb-data
            mount_path: /var/lib/mysql
        working_dir: /
        env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: DB_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: DB_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: DB_NAME
    volumes:
      - name: mariadb-data
        persistent_volume_claim:
          claim_name: database-volume-claim

- name: create Drupal deployment config
  openshift_v1_deployment_config:
    state: present
    name: drupal
    namespace: '{{ namespace }}'
    labels:
      app: drupal
      service: drupal
    replicas: 1
    selector:
      app: drupal
      service: drupal
    spec_template_metadata_labels:
      app: drupal
      service: drupal
    containers:
      - name: drupal
        image: registry.connect.redhat.com/bitnami/drupal-apache-php7
        imagePullPolicy: Always
        ports:
          - container_port: 8080
            protocol: TCP
        volumeMounts:
          - name: configuration
            mountPath: /bitnami/apache/conf/vhosts/drupal-vhosts.conf
            subPath: apache-conf
          - name: drupal-data
            mountPath: /bitnami/drupal
        env:
          # Database credentials
          - name: MARIADB_HOST
            value: database-service
          - name: MARIADB_PORT_NUMBER
            value: "3306"
          - name: DRUPAL_DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: DB_USER
          - name: DRUPAL_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: DB_PASSWORD
          - name: DRUPAL_DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: DB_NAME
          # Some Drupal basic data
          - name: DRUPAL_EMAIL
            valueFrom:
              secretKeyRef:
                name: drupal-secret
                key: DP_EMAIL
          - name: DRUPAL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: drupal-secret
                key: DP_PASSWORD
          - name: DRUPAL_USERNAME
            valueFrom:
              secretKeyRef:
                name: drupal-secret
                key: DP_USERNAME
    volumes:
      - name: configuration
        configMap:
          name: apache-conf
      - name: drupal-data
        persistentVolumeClaim:
          claimName: drupal-volume-claim

- name: create database service
  k8s_v1_service:
    state: present
    name: database-service
    namespace: '{{ namespace }}'
    labels:
      app: mariadb
      service: mariadb
    selector:
      app: mariadb
      service: mariadb
    ports:
      - name: mysql
        port: 3306
        target_port: 3306

- name: create Apache service
  k8s_v1_service:
    state: present
    name: apache-service
    namespace: '{{ namespace }}'
    labels:
      app: drupal
      service: drupal
    selector:
      app: drupal
      service: drupal
    ports:
      - name: web
        port: 80
        target_port: 8080

- name: create Apache route
  openshift_v1_route:
    state: present
    name: apache-route
    namespace: '{{ namespace }}'
    labels:
      app: drupal
      service: drupal
    to_name: apache-service
    spec_port_target_port: web
