- name: create database credentials as secret
  k8s_v1_secret:
    state: present
    name: database-secret
    namespace: '{{ namespace }}'
    data:
      DB_HOST: "{{ 'database-service' | b64encode }}"
      DB_NAME: "{{ db_name | b64encode }}"
      DB_PASSWORD: "{{ db_password | b64encode }}"
      DB_PORT: "{{ '3306' | b64encode }}"
      DB_TYPE: "{{ 'mysql' | b64encode }}"
      DB_USER: "{{ db_user | b64encode }}"

- name: create WordPress credentials as secret
  k8s_v1_secret:
    state: present
    name: wordpress-secret
    namespace: '{{ namespace }}'
    data:
      WP_USERNAME: "{{ wp_username | b64encode }}"
      WP_PASSWORD: "{{ wp_password | b64encode }}"

- name: create Apache config from template
  template:
    src: wordpress-vhosts.conf.j2
    dest: /tmp/wordpress-vhosts.conf

- name: create Apache configMap
  shell: oc create configmap apache-conf --from-file=apache-conf=/tmp/wordpress-vhosts.conf

- name: create database volume claim
  k8s_v1_persistent_volume_claim:
    state: present
    name: database-volume-claim
    namespace: "{{ namespace }}"
    labels:
      app: mysql
      service: mysql
    access_modes:
      - ReadWriteOnce
    resources_requests:
      storage: "{{ volume_size }}"

- name: create WordPress volume claim
  k8s_v1_persistent_volume_claim:
    state: present
    name: wordpress-volume-claim
    namespace: "{{ namespace }}"
    labels:
      app: wordpress
      service: wordpress
    access_modes:
      - ReadWriteOnce
    resources_requests:
      storage: "{{ volume_size }}"

- name: create database deployment config
  openshift_v1_deployment_config:
    state: present
    name: mysql
    namespace: '{{ namespace }}'
    labels:
      app: mysql
      service: mysql
    replicas: 1
    selector:
      app: mysql
      service: mysql
    spec_template_metadata_labels:
      app: mysql
      service: mysql
    containers:
      - name: mysql
        image: registry.access.redhat.com/rhscl/mysql-57-rhel7
        imagePullPolicy: Always
        ports:
          - container_port: 3306
            protocol: TCP
        volume_mounts:
          - name: mysql-data
            mount_path: /var/lib/mysql
        working_dir: /
        env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: DB_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: DB_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: DB_NAME
    volumes:
      - name: mysql-data
        persistent_volume_claim:
          claim_name: database-volume-claim

- name: create WordPress deployment config
  openshift_v1_deployment_config:
    state: present
    name: wordpress
    namespace: '{{ namespace }}'
    labels:
      app: wordpress
      service: wordpress
    replicas: 1
    selector:
      app: wordpress
      service: wordpress
    spec_template_metadata_labels:
      app: wordpress
      service: wordpress
    containers:
      - name: wordpress
        image: docker.io/javsalgar/bitnami-wordpress-rhel-apache-php5
        imagePullPolicy: Always
        ports:
          - container_port: 8080
            protocol: TCP
        volumeMounts:
          - name: configuration
            mountPath: /bitnami/apache/conf/vhosts/wordpress-vhosts.conf
            subPath: apache-conf
          - name: wordpress-data
            mountPath: /bitnami/wordpress
        env:
          # Database credentials
          - name: MARIADB_HOST
            value: database-service
          - name: MARIADB_PORT_NUMBER
            value: "3306"
          - name: WORDPRESS_DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: DB_USER
          - name: WORDPRESS_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: DB_PASSWORD
          - name: WORDPRESS_DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: DB_NAME
          # Some Wordpress basic data
          - name: WORDPRESS_BLOG_NAME
            value: "{{ blog_name }}"
          - name: WORDPRESS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wordpress-secret
                key: WP_PASSWORD
          - name: WORDPRESS_USERNAME
            valueFrom:
              secretKeyRef:
                name: wordpress-secret
                key: WP_USERNAME
    volumes:
      - name: configuration
        configMap:
          name: apache-conf
      - name: wordpress-data
        persistentVolumeClaim:
          claimName: wordpress-volume-claim

- name: create database service
  k8s_v1_service:
    state: present
    name: database-service
    namespace: '{{ namespace }}'
    labels:
      app: mysql
      service: mysql
    selector:
      app: mysql
      service: mysql
    ports:
      - name: mysql
        port: 3306
        target_port: 3306

- name: create Apache service
  k8s_v1_service:
    state: present
    name: apache-service
    namespace: '{{ namespace }}'
    labels:
      app: wordpress
      service: wordpress
    selector:
      app: wordpress
      service: wordpress
    ports:
      - name: web
        port: 80
        target_port: 8080

- name: create Apache route
  openshift_v1_route:
    state: present
    name: apache-route
    namespace: '{{ namespace }}'
    labels:
      app: wordpress
      service: wordpress
    to_name: apache-service
    spec_port_target_port: web
