- name: delete wordpress deployment config
  openshift_v1_deployment_config:
    name: wordpress
    namespace: '{{ namespace }}'
    state: absent

- name: delete database deployment config
  openshift_v1_deployment_config:
    name: mariadb
    namespace: '{{ namespace }}'
    state: absent

- name: delete Apache route
  openshift_v1_route:
    name: apache-route
    namespace: '{{ namespace }}'
    state: absent

- name: delete Apache service
  k8s_v1_service:
    name: apache-service
    namespace: '{{ namespace }}'
    state: absent

- name: delete database service
  k8s_v1_service:
    name: database-service
    namespace: '{{ namespace }}'
    state: absent

- name: delete database volume claim
  k8s_v1_persistent_volume_claim:
    name: database-volume-claim
    namespace: '{{ namespace }}'
    state: absent

- name: delete database credentials as secret
  k8s_v1_secret:
    name: database-secret
    namespace: '{{ namespace }}'
    state: absent
